packages:
  - packages/*
  - apps/*

catalog:
  '@latimeria/design-token': ^0.2.0
  '@rsbuild/core': ^1.4.15
  '@rsbuild/plugin-react': ^1.3.5
  '@tsconfig/recommended': ^1.0.10
  '@types/react': ^19.1.10
  '@types/react-dom': ^19.1.7
  eslint: ^9.33.0
  react: ^19.1.1
  react-aria: ^3.42.0
  react-aria-components: ^1.11.0
  react-dom: ^19.1.1
  react-icons: ^5.5.0
  typescript: ^5.9.2
  valibot: 1.1.0
  vitest: ^3.2.4

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - leveldown
  - sharp
  - unrs-resolver
  - workerd
