packages:
  - packages/*
  - apps/*

catalog:
  react: "^19.1.1"
  react-dom: "^19.1.1"
  "@types/react": "^19.1.10"
  "@types/react-dom": "^19.1.7"
  react-aria: "^3.42.0"
  react-aria-components: "^1.11.0"
  react-icons: "^5.5.0"
  "@latimeria/design-token": "^0.2.0"
  valibot: "^1.1.0"
  typescript: "^5.8.3"
  eslint: "^9.26.0"
  vitest: "^3.2.4"
  "@rsbuild/core": "^1.4.2"
  "@rsbuild/plugin-react": "^1.3.2"
  "@tsconfig/recommended": "^1.0.10"

onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - leveldown
  - sharp
  - unrs-resolver
