name: Check lint and format
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: Setup Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: npm

      - name: Restore cache
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install dependencies
        run: npm ci

      - name: build core package
        run: npx turbo run @latimeria/core#build

      - name: Run lint for JavaScript files
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: "actions/checkout@v4"

      - name: Setup Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: npm

      - name: Restore cache
        uses: "actions/cache@v4"
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Restore cache(Turborepo)
        uses: "actions/cache@v4"
        with:
          path: |
            .turbo
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
             ${{ runner.os }}-turbo-

      - name: Install dependencies
        run: npm ci

      - name: build core package
        run: npx turbo run @latimeria/core#build

      - name: Run format
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Eslint Change
