name: Check lint and format
on: ["push", "pull_request", "workflow_dispatch"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"

      - name: Setup Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: npm

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v2.1.4

      - name: Install dependencies
        run: npm ci

      - name: build core package
        run: npx turbo run @latimeria/core#build

      - name: Run lint for JavaScript files
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: "actions/checkout@v4"

      - name: Setup Node
        uses: "actions/setup-node@v4"
        with:
          node-version: 22
          cache: npm

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v2.1.4

      - name: Install dependencies
        run: npm ci

      - name: build core package
        run: npx turbo run @latimeria/core#build

      - name: Run format
        run: npm run format

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Eslint Change
