name: ci.yml
on:
  ["push", "pull_request"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'google-github-actions/auth@v2'
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_INDETITY_PROVIDER }}
