name: Website deploy
on:
  push:
    branches:
      - "master"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      pages: "write"
      id-token: "write"

    concurrency:
      group: "pages"
      cancel-in-progress: false

    steps:
      - uses: "actions/checkout@v4"

      - id: google-auth
        uses: "google-github-actions/auth@v2"
        with:
          service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}
          workload_identity_provider: ${{ secrets.WORKLOAD_INDETITY_PROVIDER }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: "actions/setup-node@v4"
        with:
          node-version: ">=22 <22.18"
          cache: pnpm

      - name: Setup Pages
        # See: https://github.com/actions/configure-pages/issues/171
        uses: Janealter/configure-pages@v1
        with:
          static_site_generator: next
          generator_config_file: "./apps/web/next.config.mjs"

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v2.1.4

      - name: Install dependencies
        run: pnpm install

      - name: Get public images
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=${{ steps.google-auth.outputs.credentials_file_path }} pnpm run syncPublic -- --noOAuth

      - name: build core package
        run: pnpm turbo run @latimeria/core#build @latimeria/ganoine#build

      - name: Build with Next.js
        run: pnpm run build

      - name: Upload artifact
        uses: "actions/upload-pages-artifact@v3"
        with:
          path: ./apps/web/out

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: "actions/deploy-pages@v4"
